using System;

namespace Simulation.Edit
{
    [Serializable]
    public class GridCell
    {
        private int _x;
        private int _y;
       public GridCell(int x, int y)
        {
            _x = x;
            _y = y;
        }

        public override bool Equals(object obj)
        {
            return obj is GridCell cell &&
                   _x == cell._x &&
                   _y == cell._y;
        }

        //Generated by Visual Studio IDE to make Hashtable function(s) work properly
        public override int GetHashCode()
        {
            int hashCode = 979593255;
            hashCode = hashCode * -1521134295 + _x.GetHashCode();
            hashCode = hashCode * -1521134295 + _y.GetHashCode();
            return hashCode;
        }
    }
}
